server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3306/projetocrm}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
jwt.secret=${JWT_SECRET:MinhaChaveSuperSecretaCrmMariaDB2024XYZ}
jwt.expiration=${JWT_EXPIRATION:86400000}